### ISSUE TITLE
[RFE] Set UOR specific mediatype on UOR Manifests

### ISSUE THREAD

**Issue by afflom** [emporous/emporous-go#36]
**What is the problem you're trying to solve**
The UOR manifests need a unique mediatype

**Describe the solution you'd like**
Set UOR Collection manifests to application.vnd.uor.manifest.v1+json mediatype

**Comment by jpower432** [comment]
@afflom Is this still relevant, or is a custom media type for the manifest config sufficient?

**Comment by afflom** [comment]
We might want to hold off until the dust settles from this: https://github.com/opencontainers/wg-reference-types/issues/64

**Comment by afflom** [comment]
looks like they voted to include `artifactType` in artifact manifests. Not sure what that means for us in this situation.

**Comment by jpower432** [comment]
Closing this. A media type for manifest are specified in the [collection-spec](https://github.com/emporous/collection-spec/blob/main/specs-go/v1alpha1/manifest.go) repository.
